inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
Layout/LineLength:
  Exclude:
    - 'spec/**/*'
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true